-- MySQL Script generated by MySQL Workbench
-- 11/28/16 06:49:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema teclabmanager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `teclabmanager` ;

-- -----------------------------------------------------
-- Schema teclabmanager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teclabmanager` DEFAULT CHARACTER SET utf8 ;
USE `teclabmanager` ;

-- -----------------------------------------------------
-- Table `teclabmanager`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teclabmanager`.`rooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teclabmanager`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teclabmanager`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `userpass` VARCHAR(40) NULL,
  `fullname` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teclabmanager`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teclabmanager`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `start` VARCHAR(20) NULL,
  `end` VARCHAR(20) NULL,
  `rooms_id` INT NULL,
  `users_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_rooms_idx` (`rooms_id` ASC),
  INDEX `fk_events_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_events_rooms`
    FOREIGN KEY (`rooms_id`)
    REFERENCES `teclabmanager`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `teclabmanager`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `teclabmanager`.`rooms`
-- -----------------------------------------------------
START TRANSACTION;
USE `teclabmanager`;
INSERT INTO `teclabmanager`.`rooms` (`id`, `name`) VALUES (701, '701');
INSERT INTO `teclabmanager`.`rooms` (`id`, `name`) VALUES (702, '702');
INSERT INTO `teclabmanager`.`rooms` (`id`, `name`) VALUES (703, '703');

COMMIT;


-- -----------------------------------------------------
-- Data for table `teclabmanager`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `teclabmanager`;
INSERT INTO `teclabmanager`.`users` (`id`, `username`, `userpass`, `fullname`) VALUES (1, 'lbueno', 'tecsup', 'Luis Bueno Torres');
INSERT INTO `teclabmanager`.`users` (`id`, `username`, `userpass`, `fullname`) VALUES (2, 'lmaza', 'tecsup', 'Luis Maza Arnao');

COMMIT;


-- -----------------------------------------------------
-- Data for table `teclabmanager`.`events`
-- -----------------------------------------------------
START TRANSACTION;
USE `teclabmanager`;
INSERT INTO `teclabmanager`.`events` (`id`, `title`, `start`, `end`, `rooms_id`, `users_id`) VALUES (1, 'Seguridad Informática I', '2016-12-02T16:00:00', '2016-12-02T17:00:00', 701, 2);
INSERT INTO `teclabmanager`.`events` (`id`, `title`, `start`, `end`, `rooms_id`, `users_id`) VALUES (2, 'Comunicación Inalámbrica', '2016-11-29T16:00:00', '2016-11-29T17:00:00', 701, 2);
INSERT INTO `teclabmanager`.`events` (`id`, `title`, `start`, `end`, `rooms_id`, `users_id`) VALUES (3, 'Desarrollo de Apliaciones Web', '2016-11-28T10:30:00', '2016-11-28T12:30:00', 701, 2);
INSERT INTO `teclabmanager`.`events` (`id`, `title`, `start`, `end`, `rooms_id`, `users_id`) VALUES (4, 'Charla de Inducción', '2016-11-30T12:00:00', '2016-11-30T13:00:00', 701, 2);
INSERT INTO `teclabmanager`.`events` (`id`, `title`, `start`, `end`, `rooms_id`, `users_id`) VALUES (5, 'Presentación Exitosa', '2016-11-30T14:30:00', '2016-11-30T15:30:00', 701, 2);
INSERT INTO `teclabmanager`.`events` (`id`, `title`, `start`, `end`, `rooms_id`, `users_id`) VALUES (6, 'Sistemas Operativos II', '2016-12-01T17:30:00', '2016-12-01T18:30:00', 701, 2);
INSERT INTO `teclabmanager`.`events` (`id`, `title`, `start`, `end`, `rooms_id`, `users_id`) VALUES (7, 'Diseño de Videojuegos', '2016-12-02T20:00:00', '2016-12-02T21:00:00', 701, 2);
INSERT INTO `teclabmanager`.`events` (`id`, `title`, `start`, `end`, `rooms_id`, `users_id`) VALUES (8, 'Redes Satelitales', '2016-11-29T09:00:00', '2016-11-29T10:00:00', 701, 2);

COMMIT;

